In [1]:
# numpy提供了两种基本的类ndarray和ufunc
# ndarray是存储单一数据类型的多维数组，
# ufunc是能够对数组进行处理的函数；
# 函数库导入
import numpy as np

In [8]:
# 创建数组
a = np.array([1,2,3,4])
b = np.array((5,6,7,8))
c = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
for x in "abc":
    print("%s:\n" % x, eval(x))
    print("%s.type: " % x, eval(x).dtype)
    print("%s.shape: " % x, eval(x).shape)
    print("%s.ndim: " % x, eval(x).ndim)
# reshape()可以创建一个改变了型的新数组，原数组的shape保持不变
d = np.arange(12).reshape(3,4)
d.shape = 4,3
d

a:
 [1 2 3 4]
a.type:  int32
a.shape:  (4,)
a.ndim:  1
b:
 [5 6 7 8]
b.type:  int32
b.shape:  (4,)
b.ndim:  1
c:
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
c.type:  int32
c.shape:  (3, 4)
c.ndim:  2
d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
d.type:  int32
d.shape:  (3, 4)
d.ndim:  2


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
a = np.array([1,2,3,4])
b = np.arange(5)
print("type(a): ", type(a))
print("type(b): ", type(b))

type(a):  <class 'numpy.ndarray'>
type(b):  <class 'numpy.ndarray'>


In [10]:
print("b.shape: ", b.shape)

b.shape:  (5,)


In [11]:
c = b.reshape(1,5)
print("c: \n", c)

c: 
 [[0 1 2 3 4]]


In [12]:
print("c.shape: ", c.shape)

c.shape:  (1, 5)


In [15]:
# 原数组和reshape后数组共享数据，因此修改其中一个元素的值
# 会导致另一个数组中也能看到变化
b[1] = 100
print("b: \n", b)
print("c: \n", c)

b: 
 [  0 100   2   3   4]
c: 
 [[  0 100   2   3   4]]


In [16]:
# arange函数可以通过制定开始值终止值和步长来创建一维数组
# 数组不包括终值
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# linspace函数创建等差数列
# 可以通过指定开始值终值和元素个数来创建一维数组
# 注意和arange的区别是第3个参数是表示元素个数而不是步长
# linspace可以通过endpoint参数指定是否包含终值，缺省是包含的
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
np.linspace(0,1,10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [19]:
# logspace函数和linspace类似，不过他创建等比数列
np.logspace(0,2,20)

array([  1.        ,   1.27427499,   1.62377674,   2.06913808,
         2.6366509 ,   3.35981829,   4.2813324 ,   5.45559478,
         6.95192796,   8.8586679 ,  11.28837892,  14.38449888,
        18.32980711,  23.35721469,  29.76351442,  37.92690191,
        48.32930239,  61.58482111,  78.47599704, 100.        ])

In [20]:
# empty(),ones(),empty()也可以创建指定型的数组
np.empty((2,3), np.int)

array([[242,   0,   0],
       [  0,   0,   0]])

In [21]:
np.zeros(4, np.float)

array([0., 0., 0., 0.])

In [24]:
# zeros_like(),ones_like(),empty_like()函数可以创建
# 与参数数组型一样的数组
np.ones_like(c)

array([[1, 1, 1, 1, 1]])

In [27]:
# frombuffer(),fromstring(),fromfile(),fromfunction()等
# 可以从数组，字节序列，文件，函数等创建数组
def func(i):
    return i%4 + 1
np.fromfunction(func, (10,))

array([1., 2., 3., 4., 1., 2., 3., 4., 1., 2.])

In [29]:
# 9*9乘法表
def func2(i, j):
    return (i+1) * (j+1)
a = np.fromfunction(func2, (9,9))
print(a)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 9. 18. 27. 36. 45. 54. 63. 72. 81.]]


In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a[5]

5

In [33]:
a[3:5]

array([3, 4])

In [35]:
a[:5]

array([0, 1, 2, 3, 4])

In [36]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
a[2:4] = 100, 101
a

array([  0,   1, 100, 101,   4,   5,   6,   7,   8,   9])

In [39]:
a[1:-1:2]

array([  1, 101,   5,   7])

In [40]:
a[::-1]

array([  9,   8,   7,   6,   5,   4, 101, 100,   1,   0])

In [41]:
# 使用整数数列作为下标获得的数组不和原始数组共享数据空间
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [42]:
x[[3,3,1,8]]

array([7, 7, 9, 2])

In [43]:
b = x[np.array([3,3,1,8])]
b

array([7, 7, 9, 2])

In [44]:
b[2] = 100
b

array([  7,   7, 100,   2])

In [45]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [46]:
x[[3,5,1]] = -1,-2,-3
x

array([10, -3,  8, -1,  6, -2,  4,  3,  2])

In [49]:
# 布尔数组
x = np.arange(5, 0, -1)
x[np.array([True, False, True, False, False])]

array([5, 3])

In [50]:
x[[True, False, True, False, False]]

array([5, 3])

In [53]:
x[np.array([True, False, True, True, False])]
# 布尔数组的长度要一致

array([5, 3, 2])

In [55]:
# 布尔数组一般是使用布尔运算的ufunc函数产生的
x = np.random.rand(10)
x

array([0.17153009, 0.3845942 , 0.68355356, 0.37398615, 0.05117416,
       0.28930321, 0.87901598, 0.96527445, 0.03278692, 0.23544901])

In [56]:
x > 0.5
# 得到一个布尔数组

array([False, False,  True, False, False, False,  True,  True, False,
       False])

In [58]:
x[x > 0.5]

array([0.68355356, 0.87901598, 0.96527445])

In [62]:
# 多维数组
a = np.arange(0, 60, 10).reshape(6,1) + np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [63]:
a[0, 3:5]

array([3, 4])

In [64]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [65]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [66]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [67]:
a1 = np.arange(0, 60, 10).reshape(-1, 1)
a1

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [68]:
a2 = np.arange(0,6)
a2

array([0, 1, 2, 3, 4, 5])

In [69]:
a = a1 + a2
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [70]:
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [71]:
a[3:, [ 0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [72]:
mask = np.array([1,0,1,0,0,1], dtype=np.bool)
a[mask, 2]

array([ 2, 22, 52])

In [87]:
# 结构数组
import numpy as np
persontype = np.dtype({
    "names":['name', 'age', 'weight'],
    "formats": ['S32', 'i', 'f']
    })
a = np.array([("Zhang", 32, 75.5),("Wang", 24, 65.2)], dtype=persontype)
a.dtype
# | 表示忽略字节顺序
# < 低位字节在前
# > 高位字节在前

dtype([('name', 'S32'), ('age', '<i4'), ('weight', '<f4')])

In [88]:
a[0]

(b'Zhang', 32, 75.5)

In [89]:
a[0].dtype

dtype([('name', 'S32'), ('age', '<i4'), ('weight', '<f4')])

In [90]:
c = a[1]
c["name"] = "Li"
a[1]

(b'Li', 24, 65.2)

In [92]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
a.resize(1,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [95]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
a.shape = (1,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [97]:
a.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [98]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
np.sum(a)

66

In [100]:
np.sum(np.sum(a, axis=1), axis=0)

66

In [101]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
idx = np.unravel_index(7, a.shape)
idx

(1, 3)

In [104]:
a = np.array([[7,1,9,6,3],[5,1,3,8,2],[9,8,9,4,0],[9,5,1,7,0]])
a

array([[7, 1, 9, 6, 3],
       [5, 1, 3, 8, 2],
       [9, 8, 9, 4, 0],
       [9, 5, 1, 7, 0]])

In [105]:
idx = np.argmax(a, axis=1)
idx

array([2, 3, 0, 0], dtype=int32)

In [106]:
a[idx]

array([[9, 8, 9, 4, 0],
       [9, 5, 1, 7, 0],
       [7, 1, 9, 6, 3],
       [7, 1, 9, 6, 3]])

In [107]:
idx = np.argmin(a, axis=0)
idx

array([1, 0, 3, 2, 2], dtype=int32)

In [108]:
a[idx]

array([[5, 1, 3, 8, 2],
       [7, 1, 9, 6, 3],
       [9, 5, 1, 7, 0],
       [9, 8, 9, 4, 0],
       [9, 8, 9, 4, 0]])

In [110]:
a

array([[7, 1, 9, 6, 3],
       [5, 1, 3, 8, 2],
       [9, 8, 9, 4, 0],
       [9, 5, 1, 7, 0]])

In [109]:
# 选出每行最大值
idx = np.argmax(a, axis=1)
a[range(a.shape[0]), idx]

array([9, 8, 9, 9])

In [125]:
a = np.array(
      [[7, 1, 9, 6, 3],
       [5, 1, 3, 8, 2],
       [9, 8, 9, 4, 0],
       [9, 5, 1, 7, 0]])
idx = np.argmin(a, axis=0)
a = a.transpose()
a[range(a.shape[0]), idx]

array([5, 1, 1, 4, 0])

In [126]:
a2 = np.floor(10*np.random.random((2,2)))
a2

array([[8., 5.],
       [2., 6.]])

In [127]:
b2 = np.floor(10*np.random.random((2,2)))
b2

array([[7., 1.],
       [2., 8.]])

In [128]:
np.hstack((a2,b2))

array([[8., 5., 7., 1.],
       [2., 6., 2., 8.]])

In [129]:
np.hstack((a2,b2)).shape

(2, 4)

In [130]:
np.vstack((a2,b2))

array([[8., 5.],
       [2., 6.],
       [7., 1.],
       [2., 8.]])

In [131]:
np.vstack((a2,b2)).ravel()

array([8., 5., 2., 6., 7., 1., 2., 8.])

In [132]:
np.vstack((a2,b2)).ravel().shape

(8,)