In [1]:
"""
pandas含有使数据分析工作变得更快更简单的高级数据结构和操作工具.
它是基于NumPy构建的,让以NumPy为中心的应用变得更加简单.
numpy适合处理同质型的数值类数组数据,pandas更适合用来处理表格型或异质型数据.
"""
import numpy as np
import pandas as pd
from pandas import Series, DataFrame 
# pandas 中两个常用的数据结构 Series,DataFrame

In [2]:
# Series是一种一维数组型对象,它包含了一个值序列,以及一组与之相关的数据标签(即索引).
# 仅由一组数据即可创建最简单的Series.
obj = Series([4, 7, -5, 3])
# 交互环境中Series的字符串表示形式为:索引在左边,值在右边.
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
# 由于没有为数据指定索引,于是默认生成的索引是从0到N-1(N为数据的长度);
# 可以通过Series的 values 和 index 属性分别获得Series对象的值和索引对象.
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# 通常希望所创建的Series带有一个可以对各个数据点进行标识的索引
obj2 = Series([4, 7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
# 与普通NumPy数组相比,可以通过标签来进行索引,来获取Series中的单个或一组值
obj2["a"]

-5

In [8]:
obj2["d"] = 6
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [9]:
# NumPy数组风格的操作(如根据布尔型数组进行过滤,标量乘法,应用数学函数等)都会保留索引和值之间的链接
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
# 还可以将Series看成是一个定长的有序字典,因为它是索引值到数据值的一个映射.
# 它可以用在许多原本需要字典参数的函数中.
"b" in obj2

True

In [14]:
"e" in obj2

False

In [15]:
# 如果数据被存放在一个Python字典中,也可以直接通过这个字典来创建Series.
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
# 如果只传入一个字典,则结果Series中的索引就是原字典的键(Series再有序排列).
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
# 可以通过传递一个有序列表作为索引来指定索引顺序
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
# sdata 跟 states 索引相匹配的那3个值会被找出来并放到相应的位置上
# 由于California所对应的sdata值找不到,所以其结果就为NaN(即"非数字"(not a number))
# 在pandas中使用 NaN 表示缺失(missing)或 NA 值.
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
# pandas 的 isnull() 和 notnull() 函数可用于检测缺失数据
pd.isnull(obj4) # Series也有类似的实例方法 obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
# Series 在数学操作中会自动对齐索引.
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
print("obj3: \n", obj3, "\n")
print("obj4: \n", obj4, "\n")
print("obj3 + obj4: \n", obj3 + obj4)

obj3: 
 Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64 

obj4: 
 California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64 

obj3 + obj4: 
 California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [20]:
# Series对象本身及其索引都有一个name属性.
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [21]:
# Series的索引可以通过按位赋值的方式就地修改
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [22]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [23]:
# DataFrame
# DataFrame是一个表格型的数据结构,它含有一组有序的列,每列可以是不同的值类型(数值,字符串,布尔值等).
# DataFrame既有行索引也有列索引,它可以被看做由Series组成的字典(共享相同索引).
# 跟其他类似的数据结构相比(如R的data.frame),DataFrame中面向行和面向列的操作基本上是平衡的.
# 其实,DataFrame中的数据是以一个或多个二维块存放的(而不是列表,字典或別的一维数据结构的集合).
# 尽管DataFrame是二维的,但可以利用分层索引在DataFrame中展现更高维度的数据.

# 构建DataFrame的办法有很多,最常用的一种是利用包含等长列表(或NumPy数组)组成的字典
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
      'year':[2000, 2001, 2002, 2001, 2002],
      'pop':[1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
# 产生的DataFrame会自动加上索引(跟Series一样),且全部列会被有序悱列.
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [24]:
# 如果指定了列序列,则DataFrame的列就会按照指定顺序迸行排列
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [25]:
# 跟Series一样,如果传入的列在数据中找不到,就会产生NA值
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                    index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [26]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [27]:
# 通过类似字典标记或属性的方式,可以将DataFrame的列检索为一个Series
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [28]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [29]:
# 注意,返冋的Series拥有原DataFrame相同的索引,且其name属性也已经被相应地设置好了;
# 行也可以通过位置或名称的方式进行获取,比如用索引字段iloc或loc
"""
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing
"""
frame2.loc["three"]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [30]:
# 列可以通过赋值的方式进行修改.例如,可以给那个空的"debt"列赋上一个标量值或一组值
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [31]:
frame2['debt'] = np.arange(5)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [32]:
# 将列表或数组赋值给某个列时,其长度必须跟DataFrame的长度相匹配.
# 如果赋值的是一个Series,就会精确匹配DataFrame的索引,所有的空位都将被填上缺失值.
val = Series([-1.2, -1.5, -1.7], index=[ 'two', 'four', 'five'])
frame2["debt"] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [33]:
# 为不存在的列赋值会创建出一个新列
frame2['eastern'] = (frame2.state == 'Ohio')
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [34]:
# 关键字del用于删除列
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [35]:
# 另一种常见的数据形式是嵌套字典(也就是字典的字典)
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002:3.6}}
# 如果将它传给DataFrame,就会被解释为:最外层字典的键作为列标签,内层键则作为行索引.
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [36]:
frame3.T # 可以对该结果进行转置

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [37]:
# 内层字典的键会被合并,排序以形成最终的索引.
# 如果显式指定了索引,则不会这样
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [38]:
# 包含Series的字典也可以用于构造DataFrame
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [39]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [40]:
# 如果设置了DataFrame的index和columns的name属性,则这些name属性也会被显示出来
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [41]:
# 跟Series一样,values属性也会以二维ndarray的形式返回DataFrame中的数据
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [42]:
# 如果DataFrame各列的数据类型不同,则值数组的数据类型就会选用能兼容所有列的数据类型
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [43]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [44]:
# 索引对象
# pandas的索引对象负责管理轴标签和其他元数据(比如轴名称等);
# 构建Series或DataFrame时,所用到的任何数组或其他序列的标签都会被转换成一个Index
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [45]:
index[1:]

Index(['b', 'c'], dtype='object')

In [46]:
# Index对象是不可变的(immutable),因此用户不能对其进行修改
# index[1] = "d" # error

In [47]:
# 不可变性非常重要,因为这样才能使Index对象在多个数据结构之间安全共享
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [48]:
# 除了长得像数组,Index的功能也类似一个固定大小的集合
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [49]:
'Ohio' in frame3.columns

True

In [50]:
2003 in frame3.index

False

In [51]:
# 每个索引都有一些集合逻辑的方法和属性,它们可用于设置逻辑并回答有关该索引所包含的数据的常见问题
"""
方法 说明
append   连接另一个Index对象，产生一个新的Index
diff     计算差集，并得到一个Index
intersection 计算交集
union   计算并集
isin    计算一个指示各值是否都包含在参数集合中的布尔型数组
delete  删除索引i处的元素，并得到新的Index
drop    删除传入的值，并得到新的Index
insert  将元素插入到索引i处，并得到新的Index
is_monotonic 当各元素均大于等于前一个元素时，返回True
is.unique 当Index没有重复值时，返回True
unique   计算Index中唯一值的数组
"""
frame3.index.isin([2001, 2002, 2003])

array([ True,  True, False])

In [52]:
# 重建索引
# pandas对象的一个重要方法是reindex,其作用是创建一个适应新索引的新对象
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [53]:
# 调用该Series的reindex将会根据新索引进行重排,如果某个索引值当前不存在,就引入缺失值
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [54]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [55]:
# 对于时间序列这样的有序数据,重新索引时可能需要做一些插值处理;
# method选项即可达到此目的,例如,使用ffill可以实现前向值填充
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [56]:
"""
reindex的(插值)method选项
参数                  说明
ffill或pad          前向填充（或搬运）值
bfill或backfill     后向填充（或搬运）值
"""
# 对于DataFrame,reindex可以修改(行)索引,列或两个都修改.
frame = DataFrame(np.arange(9).reshape((3, 3)),
                  index=['a', 'c', 'd'],
                  columns=[ 'Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [57]:
# 如果reindex仅传入一个序列,则会重新索引行
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [58]:
# 使用columns关键字重新索引列
states=['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [59]:
# 也可以同时对行和列进行重新索引,而插值则只能按行应用(即轴0)
# frame.reindex(index=["a","b","c","d"], columns=states，method="ffill") # 填充对索引类型有要求
# 利用loc的标签索引功能,重新索引任务可以变得更简洁
# frame.loc[['a', 'b', 'c', 'd'], states] #最新版本验证失败

In [60]:
t="""reindex函数的参数 
参数        说明
index        用作索引的新序列.可以是index实例,也可以是其他序列型的python数据结构,索引使用时无须复制.
method       插值(填充)方式.
fill_value   在重新索引的过程中,需要引入缺失值时使用的替代值.
limit        前向或后向填充时的最大填充量.
level        在MultiIndex的指定级别上匹配简单索引,否则选取其子集.
copy         如果为True,无论如何都复制;如果为False,当新旧索引相同时就不复制.
"""

In [61]:
# 丢弃指定轴上的项
"""
丢弃某条轴上的一个或多个项很简单,只要有一个索引数组或列表即可.
由于需要执行一些数据整理和集合逻辑,所以drop方法返回的是一个在指定轴上删除了指定值的新对象
"""
obj = Series(np.arange(5,), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [62]:
# 对于DataFrame,可以刪除任意轴上的索引值
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [63]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [64]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [65]:
# 索引,选取和过滤
# Series的索引(obj[...])与NumPy数组索引的功能类似,只不过Series的索引值不仅仅是整数
obj = Series(np.arange(4,), index=['a', 'b', 'c', 'd'])
obj["b"]

1

In [66]:
obj[1]

1

In [67]:
obj[2:4]

c    2
d    3
dtype: int32

In [68]:
obj = Series(np.arange(4,), index=['a', 'b', 'c', 'd'])
# 回顾一下numpy的神奇索引
# 神奇索引是numpy中的术语,用于描述使用整数数组进行数据索引;
# 神奇索引即使用整数序列作为下标获得新数组,不和原始数组共享数据空间;
# 神奇索引与切片不同,神奇索引总是将数据复制到一个新的数组中;
obj[['b', 'a', 'd']]

b    1
a    0
d    3
dtype: int32

In [69]:
obj[[1, 3]]

b    1
d    3
dtype: int32

In [70]:
obj[obj < 2]

a    0
b    1
dtype: int32

In [71]:
# 利用标签的切片运算与普通的Python切片运算不同,当使用非整数作为切片索引时,其末端是包含的（inclusive).
obj['b': 'c']

b    1
c    2
dtype: int32

In [72]:
# 使用这些方法设置时会修改Series相应的部分
obj['b':'c'] = 5
obj

a    0
b    5
c    5
d    3
dtype: int32

In [73]:
# 对DataFrame进行索引其实就是获取一个或多个列
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [74]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [75]:
# 这种索引方式有几个特殊的情况
# 首先通过切片或布尔型数组选取行
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [76]:
# 另一种用法是通过布尔型DataFrame(比如下面这个由标量比较运算得出的)进行索引
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [77]:
# 这段代码的目的是使DataFrame在语法上更像ndarray
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [78]:
data[data['three'] > 5]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [79]:
# 为了在DataFrame的行上进行标签索引,引入了专门的索引字段iloc与loc;
# 它可以通过 NumPy式的标记法以及轴标签从DataFrame中选取行和列的子集;
# 这也是一种重新索引的简单手段;
# loc 和 iloc 运算符分别用于严格处理基于标签和基于整数的索引.
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [80]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [81]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [82]:
data.loc[data.three > 5][:3]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
# DataFrame的索引选项
t="""
类型                   说明
obj[val]              选取单列或多列;特殊情况的便利:布尔型数组(过滤行),切片(行切片),布尔值DataFrame;
obj.loc[val]          根据标签选取单行或多行;
obj.loc[:, val]       根据标签选取单列或多列;
obj.loc[val1, val2]   根据标签同时选取行和列中的一部分;
obj.iloc[where]       根据整数位置选取单行或多行;
obj.iloc[:, where]    根据整数位置选取单列或多列;
obj.iloc[where_i, where_j] 根据整数位置同时选取行和列中的一部分;
obj.at[label_i, label_j]  根据行列标签选择当个标量值;
obj.iat[i, j]        根据行列整数位置选择当个标量值;
reindex 方法         将一个或多个轴匹配到新索引;
xs方法               根据标签选取行或列,并返回一个Series;
get_value,set_value方法  根据行标签和列标签选取或设置单个值;
"""

In [84]:
"算术运算和数据对齐"
"""pandas最重要的一个功能是，它可以对不同索引的对象进行算术运算
。在将对象相加时， 如果存在不同的索引对，则结果的索引就是该索
引对的并集"""
s1 = Series([7.3, -2.5, 3.4, 1.5],index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [85]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [86]:
"""自动的数据对齐操作在不重叠的索引处引入NA值。缺失值会在算术运算
过程中传播。"""
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [87]:
"对于DataFrame,对齐操作会同时发生在行和列上"
df1 = DataFrame(np.arange(9,).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12,).reshape((4, 3)), columns=list('bde'), 
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [88]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [89]:
"""把它们相加后将会返回一个新的DataFrame，其索引和列为
原来那两个DataFrame的并集
"""
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [90]:
"在算术方法中填充值"
"""在对不同索引的对象进行算术运算时，可能希望当一个对象中某个
轴标签在另一个对象中找不到时填充一个特殊值（比如0)"""
df1 = DataFrame(np.arange(12).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [91]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [92]:
"# 将它们相加时，没有重叠的位置就会产生NA值"
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [93]:
"使用df1的add方法，传入df2以及一个fill_value参数"
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [94]:
"与此类似，在对Series或DataFrame重新索引时，也可以指定一个填充值"
"""
 add             用于加法(+ )的方法
 sub             用于减法(-）的方法
 div             用于除法(/)的方法
 mul             用于乘法(*)的方法 
"""
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [95]:
"DataFrame和Series之间的运算"
"""跟NumPy数组一样，DataFrame和Series之间算术运算也是有明确规定的。
先来看一个具有启发性的例子，计算一个二维数组与其某行之间的差"""
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [96]:
arr[0]

array([0., 1., 2., 3.])

In [97]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [98]:
"这就叫做广播（broadcasting)。DataFrame和Series之间的运算差不多也是如此"
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [99]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [100]:
""" 默认情况下，DataFrame和Series之间的算术运算会将Series的索引匹
配到DataFrame的列，然后沿着行一直向下广播"""
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [101]:
"""如果某个索引值在DataFrame的列或Series的索引中找不到，则参与运
算的两个对象就会被重新索引以形成并集"""
series2 = Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [102]:
"如果希望匹配行且在列上广播，则必须使用算术运算方法。例如"
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [103]:
"""传入的轴号就是希望匹配的轴。在本例中目的是匹配DauFrame的行索
引并进行广播"""
frame.sub(series3,  axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [104]:
"函数应用和映射"
"NumPy的ufuncs (元素级数组方法）也可用于操作pandas对象"
frame = DataFrame(np.random.randn(4, 3),
                  columns=list('bde'), 
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.132407  0.863083 -1.630833
Ohio    0.855051  0.257720  0.626802
Texas  -0.169768 -0.438871 -1.158677
Oregon  1.089887 -1.337333 -0.216930

In [105]:
np.abs(frame)

b         d         e
Utah    0.132407  0.863083  1.630833
Ohio    0.855051  0.257720  0.626802
Texas   0.169768  0.438871  1.158677
Oregon  1.089887  1.337333  0.216930

In [106]:
"""另一个常见的操作是，将函数应用到由各列或行所形成的一维数组
上。DataFrame的 apply方法即可实现此功能"""
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.259655
d    2.200417
e    2.257635
dtype: float64

In [107]:
"""许多最为常见的数组统计功能都被实现成DataFrame的方法（如sum和
mean)，因此无需使用apply方法"""
frame.apply(f, axis=1)

Utah      2.493917
Ohio      0.597331
Texas     0.988909
Oregon    2.427220
dtype: float64

In [108]:
"除标量值外，传递给apply的函数还可以返回由多个值组成的Series"
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])
frame

b         d         e
Utah    0.132407  0.863083 -1.630833
Ohio    0.855051  0.257720  0.626802
Texas  -0.169768 -0.438871 -1.158677
Oregon  1.089887 -1.337333 -0.216930

In [109]:
frame.apply(f)

b         d         e
min -0.169768 -1.337333 -1.630833
max  1.089887  0.863083  0.626802

In [110]:
"""此外，元素级的Python函数也是可以用的。假如想得到frame中各个浮
点值的格式化字符串，使用applymap即可"""
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah     0.13   0.86  -1.63
Ohio     0.86   0.26   0.63
Texas   -0.17  -0.44  -1.16
Oregon   1.09  -1.34  -0.22

In [111]:
"之所以叫做applymap，是因为Series有一个用于应用元素级函数的map方法"
frame['e'].map(format)

Utah      -1.63
Ohio       0.63
Texas     -1.16
Oregon    -0.22
Name: e, dtype: object

In [112]:
"排序和排名"
"""根据条件对数据集排序(sorting)也是一种重要的内置运算。要对行或列
索引进行排序 (按字典顺序），可使用sort_index方法，它将返回一个已
排序的新对象"""
obj = Series(range(4), index=['d', 'a',  'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [113]:
"而对于DataFrame，则可以根据任意一个轴上的索引进行排序"
frame = DataFrame(np.arange(8).reshape((2, 4)),
                  index=['three', 'one'], columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [114]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [115]:
"数据默认是按升序排序的，但也可以降序排序"
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [116]:
#"若要按值对Series进行排序，可使用其order方法"
#obj = Series([4, 7, -3, 2])
#obj.order()
# AttributeError: 'Series' object has no attribute 'order'

In [117]:
#obj = Series([4, np.nan, 1, np.nan, -3, 2])
#bj.order() #在排序时，缺失值默认都会被放到Series的末尾.

In [118]:
"""在DataFrame上，可能希望根据一个或多个列中的值进行排序。将一个
或多个列的名字传递给by选项即可达到该目的"""
frame = DataFrame({'b': [4,7,-3,2], 'a':[0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [119]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [120]:
"要根据多个列进行排序，传入名称的列表即可"
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [121]:
"""排名（ranking)跟排序关系密切，且它会增设一个排名值（从1开始，
一直到数组中有 效数据的数量）。它跟numpy.argsort产生的间接排序索
引差不多，只不过它可以根据某种规则破坏平级关系。"""
"""Series和DataFrame的rank方法:默认情况下，rank是通过
“为各组分配一个平均排名”的方式破坏平级关系的"""
obj = Series([7,-5,7,4,2,0,4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [122]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [123]:
obj.rank(method='first')  #根据值在原数据中出现的顺序给出排名

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [124]:
obj.rank(ascending=False, method='max') # 按降序进行排名

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [125]:
"""
排名时用于破坏平级关系的method选项
Method                           说明
‘average’    默认：在相等分组中，为各个值分配平均排名
‘min’        使用整个分组的最小排名
‘max’        使用整个分组的最大排名
‘first’      按值在原始数据中的出现顺序分配排名 
"""
"DataFrame可以在行或列上计算排名"
frame =DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                  'c':[-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [126]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [127]:
"带有重复值的轴索引"
"带有重复索引值的Series"
obj = Series(range(5), index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [128]:
"索引的is_unique属性验证是否是唯一的"
obj.index.is_unique

False

In [129]:
"""对于带有重复值的索引，数据选取的行为将会有些不同。如果某个索引
对应多个值，则返回一个Series;  而对应单个值的，则返回一个标量值"""
obj = Series(range(5), index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [130]:
obj["a"]

a    0
a    1
dtype: int64

In [131]:
obj["c"]

4

In [132]:
"对 DataFrame 的行进行索引时也是如此"
df = DataFrame(np.random.randn(4, 3), index=['a','a','b','b'])
df

0         1         2
a  0.846064 -0.636466 -0.189702
a  0.889828  1.527894 -1.519448
b -1.693651 -1.214325 -0.340766
b  0.597147 -0.004533 -1.332628

In [133]:
df.loc["b"]

0         1         2
b -1.693651 -1.214325 -0.340766
b  0.597147 -0.004533 -1.332628